CREATE TABLE IF NOT EXISTS raw_current_weather (
    id integer primary key generated always as identity,
    ingestion_timestamp_utc timestamp without time zone default (now() at time zone 'utc'),
    latitude decimal(9, 6),
    longitude decimal(9, 6),
    weather jsonb,
    base varchar(255),
    main_temp_c decimal(9, 2),
    main_feels_like_c decimal(9, 2),
    main_pressure_hpa integer,
    main_humidity integer,
    main_temp_min_c decimal(9, 2),
    main_temp_max_c decimal(9, 2),
    main_sea_level_hpa integer,
    main_grnd_level_hpa integer,
    wind_speed_m_s decimal(9, 2),
    wind_deg decimal(9, 2),
    wind_gust_m_s decimal(9, 2),
    clouds_all decimal(9, 2),
    rain_1h_mm decimal(9, 2),
    rain_3h_mm decimal(9, 2),
    snow_1h_mm decimal(9, 2),
    snow_3h_mm decimal(9, 2),
    dt_datetime_utc timestamp,
    sys_type integer,
    sys_id integer,
    sys_message varchar(255),
    sys_country varchar(255),
    sys_sunrise_utc timestamp,
    sys_sunset_utc timestamp,
    timezone_offset integer,
    city_id integer,
    city_name varchar(255),
    cod integer
);