INSERT INTO raw_current_weather (
        latitude,
        longitude,
        weather,
        base,
        main_temp_c,
        main_feels_like_c,
        main_pressure_hpa,
        main_humidity,
        main_temp_min_c,
        main_temp_max_c,
        main_sea_level_hpa,
        main_grnd_level_hpa,
        wind_speed_m_s,
        wind_deg,
        wind_gust_m_s,
        clouds_all,
        rain_1h_mm,
        rain_3h_mm,
        snow_1h_mm,
        snow_3h_mm,
        dt_datetime_utc,
        sys_type,
        sys_id,
        sys_message,
        sys_country,
        sys_sunrise_utc,
        sys_sunset_utc,
        timezone_offset,
        city_id,
        city_name,
        cod
    )
VALUES (
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value")["coord"]["lat"] }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value")["coord"]["lon"] }},
        '{{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value")["weather"] }}',
        '{{ ti.xcom_pull(task_ids='ingest_api_data', key='return_value')["base"] }}',
        {{ ti.xcom_pull(task_ids='ingest_api_data', key='return_value').get("main",dict()).get("temp","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("main",dict()).get("feels_like","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("main",dict()).get("pressure","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("main",dict()).get("humidity","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("main",dict()).get("temp_min","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("main",dict()).get("temp_max","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("main",dict()).get("sea_level","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("main",dict()).get("grnd_level","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("wind",dict()).get("speed","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("wind",dict()).get("deg","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("wind",dict()).get("gust","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("clouds",dict()).get("all","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("rain",dict()).get("1h","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("rain",dict()).get("3h","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("snow",dict()).get("1h","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("snow",dict()).get("3h","null") }},
        to_timestamp({{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("dt","null") }}),
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("sys",dict()).get("type","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("sys",dict()).get("id","null") }},
        '{{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("sys",dict()).get("message","") }}',
        '{{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("sys",dict()).get("country","") }}',
        to_timestamp({{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("sys",dict()).get("sunrise","null") }}),
        to_timestamp({{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("sys",dict()).get("sunset","null") }}),
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("timezone","null") }},
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("id","null") }},
        '{{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("name","") }}',
        {{ ti.xcom_pull(task_ids="ingest_api_data", key="return_value").get("cod","null") }}
    );